--- #YAML:1.0
name:                Text-TinySegmenter
version:             0.01
abstract:            Super compact Japanese tokenizer
license:             bsd
author:              
    - Jiro Nishiguchi <jiro@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
